#!/bin/sh

GF3_HOME=/usr/share/glassfish3
USER=glassfish

DOMAINS_HOME=/var/glassfish3
LOGS_DIR=/var/log/glassfish3

if [ "$GF3_HOME/glassfish/bin" ]; then
  sudo chmod a+x $GF3_HOME/glassfish/bin/*
fi

if [ ! -d "$LOGS_DIR" ]; then
  echo "creating log directory '$LOGS_DIR'"
  sudo mkdir -p $LOGS_DIR
  sudo chown $USER:$USER $LOGS_DIR
fi

if [ ! -d "$DOMAINS_HOME" ]; then
  echo "creating domains directory '$DOMAINS_HOME'"
  sudo mkdir -p $DOMAINS_HOME
  sudo chown $USER:$USER $DOMAINS_HOME
  sudo -u $USER ln -s $DOMAINS_HOME $GF3_HOME/glassfish/domains
fi

