#!/usr/bin/env bash

# creating the glassfish group and user
if [ -z "$(getent group glassfish)" ]; then
  echo "creating group 'glassfish'"
  sudo groupadd glassfish
fi
if [ -z "$(getent passwd glassfish)" ]; then
  echo "creating user 'glassfish'"
  sudo useradd --gid glassfish --comment 'Glassfish administrator' --home /usr/share/glassfish3 glassfish
fi
